### ISSUE TITLE
when will you release the code?

### ISSUE THREAD

**Issue by leechaonan** [kevinlin311tw/METRO#1]
when will you release the code?

**Comment by kevinlin311tw** [comment]
Thank you for your interests in our work.

We are now preparing the code release. It is currently under our company reviews. We hope we would be able to release it before the conference date.

**Comment by kevinlin311tw** [comment]
Please visit the link for the code release: [https://github.com/microsoft/MeshTransformer](https://github.com/microsoft/MeshTransformer)
